param(
  [ValidateSet("AR_OPS_01","ALL")]
  [string]$Phase = "AR_OPS_01",
  [switch]$Resume
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $Root "settings.ps1")
$candidateSettings = Join-Path $Root "candidate_settings.ps1"
if(Test-Path $candidateSettings){
  . $candidateSettings
}else{
  # FINALIST_MT5 uses explicit matrix values; these are compatibility-only fallbacks.
  $CandidateHighMax = 4
  $CandidateHighSL = 1.50
}

function Fail([string]$Message) {
  Write-Host "ERROR: $Message" -ForegroundColor Red
  exit 1
}
function Ensure-Path([string]$Path,[string]$Label) {
  if (-not (Test-Path $Path)) { Fail "$Label not found: $Path" }
}
function BoolText($v) {
  $t = ("$v").Trim().ToLowerInvariant()
  if ($t -in @("1","true","yes","y")) { return "true" }
  return "false"
}
function Num([string]$v) {
  if ([string]::IsNullOrWhiteSpace($v)) { return 0.0 }
  return [double]::Parse($v,[Globalization.CultureInfo]::InvariantCulture)
}
function Parse-Time([string]$s) {
  $formats = @("yyyy.MM.dd HH:mm:ss.fff","yyyy.MM.dd HH:mm:ss")
  foreach($f in $formats){
    try { return [datetime]::ParseExact($s,$f,[Globalization.CultureInfo]::InvariantCulture) } catch {}
  }
  return [datetime]::Parse($s,[Globalization.CultureInfo]::InvariantCulture)
}
function Get-EnabledRangeDates([string]$CsvPath) {
  $ds = @()
  foreach($r in (Import-Csv $CsvPath)) {
    if([string]::IsNullOrWhiteSpace($r.date)){ continue }
    $enabled = ("$($r.enabled)").Trim().ToLowerInvariant()
    if($enabled -in @("false","0","no","n")){ continue }
    $ds += [datetime]::ParseExact($r.date,"yyyy.MM.dd",[Globalization.CultureInfo]::InvariantCulture)
  }
  return @($ds | Sort-Object -Unique)
}
function Resolve-DateRange($row,$AllRangeDates) {
  $scope = ("$($row.date_scope)").Trim().ToUpperInvariant()
  if($scope -eq "ALL_RANGES") {
    if($AllRangeDates.Count -eq 0){ Fail "ranges.csv contains no enabled dates" }
    $a = $AllRangeDates[0]
    $b = $AllRangeDates[$AllRangeDates.Count-1].AddDays(1)
    return @{ From=$a.ToString("yyyy.MM.dd"); To=$b.ToString("yyyy.MM.dd") }
  }
  if($scope -eq "CUSTOM") {
    $a = ("$($row.from_date)").Trim()
    $b = ("$($row.to_date)").Trim()
    if([string]::IsNullOrWhiteSpace($a) -or [string]::IsNullOrWhiteSpace($b)){
      Fail "CUSTOM date_scope requires from_date and to_date for run $($row.run_id)"
    }
    [void][datetime]::ParseExact($a,"yyyy.MM.dd",[Globalization.CultureInfo]::InvariantCulture)
    [void][datetime]::ParseExact($b,"yyyy.MM.dd",[Globalization.CultureInfo]::InvariantCulture)
    return @{ From=$a; To=$b }
  }
  return @{ From=$FromDate; To=$ToDate }
}
function Expected-Dates-InRange($AllRangeDates,[string]$A,[string]$B) {
  $from = [datetime]::ParseExact($A,"yyyy.MM.dd",[Globalization.CultureInfo]::InvariantCulture)
  $to = [datetime]::ParseExact($B,"yyyy.MM.dd",[Globalization.CultureInfo]::InvariantCulture)
  return @($AllRangeDates | Where-Object { $_ -ge $from -and $_ -lt $to } | ForEach-Object { $_.ToString("yyyy.MM.dd") })
}
function Write-SetFile($row,[string]$Path,[int]$HighMax,[double]$HighSL) {
  $qa = BoolText $row.qa_discovery
  $dlo = BoolText $row.dl_override
  $summary = "$($row.run_id)_summary.csv"
  $journal = "$($row.run_id)_journal.csv"
  $lot = Num $row.lot
  $qaBasis = Num $row.qa_capital_basis
  $dlPct = Num $row.dl_pct
  $sessionMode = [int]$row.session_mode
  $preclose = Num $row.session_preclose_minutes
  $lines = @(
    "; AUTO-GENERATED by XAUUSD MVP Finalist MT5 Validation Harness",
    "InpRangesFile=$RangesFileName",
    "InpJournalFile=$journal",
    "InpSummaryFile=$summary",
    "InpRCapUSD=6.0||6.0||0.5||12.0||N",
    "InpQADiscoveryMode=$qa||$qa||0||false||N",
    "InpQAStrategyCapitalBasis=$qaBasis||$qaBasis||10.0||100000.0||N",
    "InpDebugVisual=false||false||0||true||N",
    "InpShowZonesOnLiveChart=false||false||0||true||N",
    "InpShowSignalTextOnLiveChart=false||false||0||true||N",
    "InpCleanupVisualOnDeinit=false||false||0||true||N",
    "InpHighReversalMaxPerDay=$HighMax||$HighMax||1||4||N",
    "InpHighReversalSLMultiplier=$HighSL||$HighSL||0.1||3.0||N",
    "InpTestVolumeLot=$lot||$lot||0.01||1.0||N",
    "InpTestDailyLossOverride=$dlo||$dlo||0||false||N",
    "InpTestDailyLossPercent=$dlPct||$dlPct||1.0||99.0||N",
    "InpFastValidationMode=$(BoolText $row.fast_validation)||$(BoolText $row.fast_validation)||0||true||N",
    "InpSessionFlatMode=$sessionMode||$sessionMode||1||2||N",
    "InpSessionPreCloseMinutes=$preclose||$preclose||1.0||15.0||N",
    "InpSessionSafetyTelemetry=true||true||0||true||N",
    "InpMVPSimpleProfile=$([int]$row.mvp_profile)||$([int]$row.mvp_profile)||1||4||N",
    "InpMaxLivePositions=$([int]$row.max_live_positions)||$([int]$row.max_live_positions)||1||99||N",
    "InpMVPProfileTelemetry=true||true||0||true||N",
    "InpPortfolioRiskMode=$([int]$row.risk_mode)||$([int]$row.risk_mode)||1||2||N",
    "InpPortfolioRiskBudgetPercent=$(Num $row.risk_pct)||$(Num $row.risk_pct)||1.0||50.0||N",
    "InpPortfolioRiskTelemetry=true||true||0||true||N",
    "InpStrategyCapitalBasisUSD=$(Num $row.capital_basis)||$(Num $row.capital_basis)||1.0||100000.0||N",
    "InpOpsRestartSafety=true||true||0||true||N",
    "InpOpsStateFile=XAUUSD_MVP_OPS_STATE_$runId.csv",
    "InpOpsSimRestartTime=$($row.restart_time)",
    "InpOpsTelemetry=true||true||0||true||N"
  )
  Set-Content -Path $Path -Value $lines -Encoding ASCII
  return @{ Summary=$summary; Journal=$journal }
}
function Write-IniFile($row,[string]$SetName,[string]$Path,[string]$RunFromDate,[string]$RunToDate) {
  $deposit = Num $row.deposit
  $expertRel = "$ExpertFolder\" + [IO.Path]::GetFileNameWithoutExtension($EAFileName)
  $lines = @(
    "[Experts]",
    "AllowLiveTrading=0",
    "AllowDllImport=0",
    "Enabled=1",
    "",
    "[Tester]",
    "Expert=$expertRel",
    "ExpertParameters=$SetName",
    "Symbol=$Symbol",
    "Period=$Period",
    "Model=$Model",
    "ExecutionMode=$ExecutionMode",
    "Optimization=0",
    "FromDate=$RunFromDate",
    "ToDate=$RunToDate",
    "Deposit=$deposit",
    "Currency=$Currency",
    "Leverage=$Leverage",
    "UseLocal=1",
    "UseRemote=0",
    "UseCloud=0",
    "Visual=0",
    "ShutdownTerminal=1"
  )
  Set-Content -Path $Path -Value $lines -Encoding ASCII
}
function Find-NewestOutput([string]$FileName,[datetime]$After) {
  # v1.1: TEST_MATRIX_IOFIX writes tester input/output with FILE_COMMON.
  # This avoids the local-agent sandbox being cleaned when the tester shuts down.
  $roots = @($CommonFilesDir) | Where-Object { Test-Path $_ }
  $hits = foreach ($r in $roots) {
    Get-ChildItem -Path $r -Recurse -File -Filter $FileName -ErrorAction SilentlyContinue |
      Where-Object { $_.LastWriteTime -ge $After.AddSeconds(-5) }
  }
  return $hits | Sort-Object LastWriteTime -Descending | Select-Object -First 1
}
function Save-Diagnostics([string]$RunDir,[datetime]$After) {
  $diagDir = Join-Path $RunDir "diagnostics"
  New-Item -ItemType Directory -Force -Path $diagDir | Out-Null
  $terminalLogDir = Join-Path $DataDir "Tester\logs"
  if(Test-Path $terminalLogDir){
    Get-ChildItem $terminalLogDir -File -Filter "*.log" -ErrorAction SilentlyContinue |
      Where-Object { $_.LastWriteTime -ge $After.AddMinutes(-2) } |
      ForEach-Object { Copy-Item $_.FullName (Join-Path $diagDir ("terminal_tester_"+$_.Name)) -Force }
  }
  # Agent root is normally under ...\MetaQuotes\Tester\<terminal-instance-id>.
  $instanceId = Split-Path $DataDir -Leaf
  $metaQuotesRoot = Split-Path (Split-Path $DataDir -Parent) -Parent
  $agentRoot = Join-Path $metaQuotesRoot "Tester\$instanceId"
  if(Test-Path $agentRoot){
    Get-ChildItem $agentRoot -Recurse -File -Filter "*.log" -ErrorAction SilentlyContinue |
      Where-Object { $_.LastWriteTime -ge $After.AddMinutes(-2) } |
      Select-Object -First 20 |
      ForEach-Object { Copy-Item $_.FullName (Join-Path $diagDir ("agent_"+$_.Directory.Name+"_"+$_.Name)) -Force }
  }
}
function Parse-KV([string]$Note,[string]$Key) {
  if ($Note -match ("(?:^|\s)" + [regex]::Escape($Key) + "=([^\s]+)")) { return $Matches[1] }
  return $null
}
function Analyze-Summary([string]$RunId,[string]$PhaseName,[double]$Deposit,[string]$SummaryPath) {
  $rows = Import-Csv $SummaryPath
  $closed = @($rows | Where-Object { $_.category -eq "PRIMARY_TRADE" -and $_.event -eq "POSITION_CLOSED" -and $_.counted_in_pnl -eq "true" })
  $fills  = @($rows | Where-Object { $_.category -eq "PRIMARY_TRADE" -and $_.event -eq "ORDER_FILLED" -and $_.counted_in_pnl -eq "true" })
  $revClosed = @($closed | Where-Object { $_.signal -like "R-*" })
  $pbClosed  = @($closed | Where-Object { $_.signal -like "PB-*" })
  $stacked   = @($closed | Where-Object { $_.stacked_pullback -eq "true" })

  function SumPnl($a) { $x=0.0; foreach($r in $a){$x += Num $r.net_pnl}; return $x }
  function Wins($a) { return @($a | Where-Object { (Num $_.net_pnl) -gt 0.01 }).Count }
  function Losses($a) { return @($a | Where-Object { (Num $_.net_pnl) -lt -0.01 }).Count }
  function Bes($a) { return @($a | Where-Object { [math]::Abs((Num $_.net_pnl)) -le 0.01 }).Count }
  function WinRate($a) { if($a.Count -eq 0){return 0.0}; return 100.0*(Wins $a)/$a.Count }

  $pnl = SumPnl $closed
  $revPnl = SumPnl $revClosed
  $pbPnl = SumPnl $pbClosed

  # High-reversal identification: the SIGNAL row contains "TEST HIGH". Map to the fill at the same timestamp/zone/signal/ordinal.
  $highKeys = @{}
  foreach($r in $rows | Where-Object { $_.event -eq "REVERSAL_SIGNAL" -and $_.note -like "TEST HIGH*" }) {
    $k = "$($r.server_time)|$($r.zone_id)|$($r.signal)|$($r.reversal_ordinal)"
    $highKeys[$k] = $true
  }
  $highTickets = @{}
  foreach($r in $fills | Where-Object { $_.signal -like "R-*" }) {
    $k = "$($r.server_time)|$($r.zone_id)|$($r.signal)|$($r.reversal_ordinal)"
    if($highKeys.ContainsKey($k)) { $highTickets[$r.position_ticket] = [int]$r.reversal_ordinal }
  }
  $highClosed = @($closed | Where-Object { $highTickets.ContainsKey($_.position_ticket) })
  $ord = @{}
  foreach($n in 1..4) {
    $arr = @($highClosed | Where-Object { $highTickets[$_.position_ticket] -eq $n })
    $ord[$n] = @{N=$arr.Count; Pnl=(SumPnl $arr); W=(Wins $arr); L=(Losses $arr); BE=(Bes $arr)}
  }

  # Concurrent position and summed initial R0 from fill/close sequence.
  $events = @($rows | Where-Object { $_.category -eq "PRIMARY_TRADE" -and $_.event -in @("ORDER_FILLED","POSITION_CLOSED") } | Sort-Object server_time)
  $open = @{}
  $maxPos=0; $maxRisk=0.0
  foreach($e in $events) {
    if($e.event -eq "ORDER_FILLED") { $open[$e.position_ticket] = (Num $e.r0) }
    elseif($e.event -eq "POSITION_CLOSED") { [void]$open.Remove($e.position_ticket) }
    $risk=0.0; foreach($v in $open.Values){$risk += [double]$v}
    if($open.Count -gt $maxPos){$maxPos=$open.Count}
    if($risk -gt $maxRisk){$maxRisk=$risk}
  }

  # Margin telemetry.
  $marginRows = @($rows | Where-Object { $_.event -in @("MARGIN_PRECHECK","MARGIN_POST_FILL") })
  $maxMargin=0.0; $minFree=[double]::PositiveInfinity; $minLevel=[double]::PositiveInfinity; $maxRequired=0.0
  foreach($m in $marginRows) {
    $am = Parse-KV $m.note "account_margin"; if($am){$v=Num $am; if($v -gt $maxMargin){$maxMargin=$v}}
    $fm = Parse-KV $m.note "free_margin"; if($fm){$v=Num $fm; if($v -lt $minFree){$minFree=$v}}
    $ml = Parse-KV $m.note "margin_level"; if($ml){$v=Num $ml; if($v -gt 0 -and $v -lt $minLevel){$minLevel=$v}}
    $rm = Parse-KV $m.note "required_new_margin"; if($rm -and $rm -ne "N/A"){$v=Num $rm; if($v -gt $maxRequired){$maxRequired=$v}}
  }
  if([double]::IsPositiveInfinity($minFree)){$minFree=0.0}
  if([double]::IsPositiveInfinity($minLevel)){$minLevel=0.0}

  $marginBlocked = @($rows | Where-Object { $_.event -eq "EXECUTION_BLOCKED_MARGIN" }).Count
  $dailyStop = @($rows | Where-Object { $_.event -eq "DAILY_LOSS_STOP" }).Count
  $dailyWould = @($rows | Where-Object { $_.event -eq "DAILY_LOSS_WOULD_TRIGGER" }).Count

  $retPct = 0.0
  $riskPct = 0.0
  if($Deposit -gt 0){
    $retPct = [math]::Round(100*$pnl/$Deposit,2)
    $riskPct = [math]::Round(100*$maxRisk/$Deposit,2)
  }
  return [pscustomobject]@{
    run_id=$RunId; phase=$PhaseName; deposit=$Deposit;
    net_pnl=[math]::Round($pnl,2); return_pct=$retPct;
    trades=$closed.Count; wins=(Wins $closed); losses=(Losses $closed); be=(Bes $closed);
    reversal_trades=$revClosed.Count; reversal_win_rate=[math]::Round((WinRate $revClosed),2); reversal_pnl=[math]::Round($revPnl,2);
    pullback_trades=$pbClosed.Count; pullback_win_rate=[math]::Round((WinRate $pbClosed),2); pullback_pnl=[math]::Round($pbPnl,2);
    high_r1_n=$ord[1].N; high_r1_pnl=[math]::Round($ord[1].Pnl,2);
    high_r2_n=$ord[2].N; high_r2_pnl=[math]::Round($ord[2].Pnl,2);
    high_r3_n=$ord[3].N; high_r3_pnl=[math]::Round($ord[3].Pnl,2);
    high_r4_n=$ord[4].N; high_r4_pnl=[math]::Round($ord[4].Pnl,2);
    stacked_trades=$stacked.Count; stacked_pnl=[math]::Round((SumPnl $stacked),2);
    max_concurrent_positions=$maxPos; peak_summed_r0=[math]::Round($maxRisk,2);
    peak_summed_r0_pct=$riskPct;
    max_required_new_margin=[math]::Round($maxRequired,2); max_account_margin=[math]::Round($maxMargin,2);
    min_free_margin=[math]::Round($minFree,2); min_margin_level=[math]::Round($minLevel,2);
    margin_blocked=$marginBlocked; daily_loss_stop=$dailyStop; daily_loss_would_trigger=$dailyWould
  }
}


function Analyze-Extended($base,[string]$RunId,[string]$PhaseName,[double]$Deposit,[double]$Lot,[int]$HighMax,[double]$HighSL,[string]$RunFrom,[string]$RunTo,[string]$SummaryPath,[string]$JournalPath,$ExpectedDates) {
  $rows = @(Import-Csv $SummaryPath)
  $jrows = @(Import-Csv $JournalPath)
  $closed = @($rows | Where-Object { $_.category -eq "PRIMARY_TRADE" -and $_.event -eq "POSITION_CLOSED" -and $_.counted_in_pnl -eq "true" } | Sort-Object server_time)
  $fills = @($rows | Where-Object { $_.category -eq "PRIMARY_TRADE" -and $_.event -eq "ORDER_FILLED" -and $_.counted_in_pnl -eq "true" })
  $revClosed = @($closed | Where-Object { $_.signal -like "R-*" })
  $pbClosed = @($closed | Where-Object { $_.signal -like "PB-*" })

  function Pnls($a){ return @($a | ForEach-Object { Num $_.net_pnl }) }
  function PosVals($a){ return @(Pnls $a | Where-Object { $_ -gt 0.01 }) }
  function NegVals($a){ return @(Pnls $a | Where-Object { $_ -lt -0.01 }) }
  function SumVals($a){ $z=0.0; foreach($v in $a){$z += [double]$v}; return $z }
  function PF($a){ $gp=SumVals (PosVals $a); $gl=-1.0*(SumVals (NegVals $a)); if($gl -le 0){if($gp -gt 0){return 9999.0}else{return 0.0}}; return $gp/$gl }
  function AvgArr($a){ if($a.Count -eq 0){return 0.0}; return (SumVals $a)/$a.Count }
  function MaxLossStreak($a){ $cur=0;$mx=0; foreach($r in $a){ if((Num $r.net_pnl) -lt -0.01){$cur++;if($cur -gt $mx){$mx=$cur}} else {$cur=0} }; return $mx }
  function RealizedDD($a){ $cum=0.0;$peak=0.0;$dd=0.0; foreach($r in $a){$cum += Num $r.net_pnl;if($cum -gt $peak){$peak=$cum};$x=$peak-$cum;if($x -gt $dd){$dd=$x}}; return $dd }

  $pvals=Pnls $closed; $pos=PosVals $closed; $neg=NegVals $closed
  $grossProfit=SumVals $pos; $grossLoss=-1.0*(SumVals $neg)

  # Daily decomposition and realized giveback.
  $daily = @()
  $dayGroups = $closed | Group-Object { $_.server_time.Substring(0,10) }
  foreach($g in $dayGroups){
    $drows=@($g.Group | Sort-Object server_time)
    $dPnl=0.0;$peak=0.0;$giveback=0.0
    foreach($r in $drows){$dPnl += Num $r.net_pnl;if($dPnl -gt $peak){$peak=$dPnl};$gb=$peak-$dPnl;if($gb -gt $giveback){$giveback=$gb}}
    $dr=@($drows|Where-Object{$_.signal -like 'R-*'});$dp=@($drows|Where-Object{$_.signal -like 'PB-*'})
    $daily += [pscustomobject]@{run_id=$RunId;phase=$PhaseName;date=$g.Name;net_pnl=[math]::Round($dPnl,2);trades=$drows.Count;reversal_trades=$dr.Count;reversal_pnl=[math]::Round((SumVals (Pnls $dr)),2);pullback_trades=$dp.Count;pullback_pnl=[math]::Round((SumVals (Pnls $dp)),2);realized_peak=[math]::Round($peak,2);max_realized_giveback=[math]::Round($giveback,2)}
  }
  $posDays=@($daily|Where-Object{$_.net_pnl -gt 0.01});$negDays=@($daily|Where-Object{$_.net_pnl -lt -0.01});$flatDays=@($daily|Where-Object{[math]::Abs($_.net_pnl)-le 0.01})
  $bestDay=0.0;$worstDay=0.0;$maxGiveback=0.0
  if($daily.Count -gt 0){$bestDay=($daily|Measure-Object net_pnl -Maximum).Maximum;$worstDay=($daily|Measure-Object net_pnl -Minimum).Minimum;$maxGiveback=($daily|Measure-Object max_realized_giveback -Maximum).Maximum}

  # Expected zone-day coverage from ranges.csv vs journal day load records.
  $loadedDates=@{}
  foreach($r in $jrows | Where-Object {$_.event -eq 'ZONES_LOADED'}){
    if($r.reason_error -match 'day=(\d{4}\.\d{2}\.\d{2})\s+final_zone_count=(\d+)'){
      if([int]$Matches[2] -gt 0){$loadedDates[$Matches[1]]=$true}
    }
  }
  $missingDates=@($ExpectedDates|Where-Object{-not $loadedDates.ContainsKey($_)})

  # b-31 de-dup audit: max one Reversal evaluation in M15 + Zone + Direction.
  $seen=@{};$dupB31=0
  foreach($r in $rows | Where-Object {$_.event -in @('REVERSAL_SIGNAL','SECONDARY_REVERSAL_CANDIDATE')}){
    $t=Parse-Time $r.server_time;$m=[math]::Floor($t.Minute/15)*15
    $bar=Get-Date -Year $t.Year -Month $t.Month -Day $t.Day -Hour $t.Hour -Minute $m -Second 0
    $k="$($bar.ToString('yyyy.MM.dd HH:mm'))|$($r.zone_id)|$($r.signal)"
    if($seen.ContainsKey($k)){$dupB31++}else{$seen[$k]=$true}
  }

  # Breakout/Pullback lineage audit.
  $bo=@{};$dupBo=0
  foreach($r in $rows | Where-Object {$_.event -eq 'BREAKOUT_SIGNAL' -and -not [string]::IsNullOrWhiteSpace($_.breakout_id)}){
    $k="$($r.server_time.Substring(0,10))|$($r.breakout_id)"; if($bo.ContainsKey($k)){$dupBo++}else{$bo[$k]=$true}
  }
  $orphanParent=0;$unknownParent=0
  foreach($r in $rows | Where-Object {$_.signal -like 'PB-*' -and $_.event -in @('PULLBACK_CYCLE_CREATED','PENDING_PLACED','ORDER_FILLED','POSITION_CLOSED','PENDING_EXPIRED')}){
    if([string]::IsNullOrWhiteSpace($r.parent_breakout_id)){$orphanParent++;continue}
    $k="$($r.server_time.Substring(0,10))|$($r.parent_breakout_id)";if(-not $bo.ContainsKey($k)){$unknownParent++}
  }

  # Fill/close lifecycle audit.
  $fillTickets=@{};foreach($r in $fills){if(-not [string]::IsNullOrWhiteSpace($r.position_ticket)){$fillTickets[$r.position_ticket]=$r}}
  $closeTickets=@{};foreach($r in $closed){if(-not [string]::IsNullOrWhiteSpace($r.position_ticket)){$closeTickets[$r.position_ticket]=$true}}
  $unclosed=0;foreach($k in $fillTickets.Keys){if(-not $closeTickets.ContainsKey($k)){$unclosed++}}

  # b-29 never-loosen audit from confirmed stop moves.
  $lastSl=@{};$side=@{};$slLoosen=0
  foreach($r in $fills){$sig=$r.signal;if($sig -in @('R-B','PB-B')){$side[$r.position_ticket]='BUY'}elseif($sig -in @('R-S','PB-S')){$side[$r.position_ticket]='SELL'};$lastSl[$r.position_ticket]=Num $r.sl}
  foreach($r in $jrows | Where-Object {$_.event -eq 'SL_MOVE_CONFIRMED'} | Sort-Object server_time){
    $tk=$r.position_ticket;if(-not $side.ContainsKey($tk)){continue};$new=Num $r.sl;$old=$lastSl[$tk]
    if($side[$tk] -eq 'BUY' -and $new + 0.00001 -lt $old){$slLoosen++}
    if($side[$tk] -eq 'SELL' -and $new - 0.00001 -gt $old){$slLoosen++}
    $lastSl[$tk]=$new
  }

  # Daily-loss stop must not be followed by new fills/pending on the same broker day.
  $postStop=0
  foreach($s in $jrows | Where-Object {$_.event -eq 'DAILY_LOSS_STOP'}){
    $st=Parse-Time $s.server_time;$day=$s.server_time.Substring(0,10)
    $postStop += @($rows|Where-Object{$_.server_time.StartsWith($day) -and $_.event -in @('PENDING_PLACED','ORDER_FILLED') -and (Parse-Time $_.server_time) -gt $st}).Count
  }

  # Daily-net reconciliation against note on last close of each day.
  $dailyMismatch=0
  foreach($g in $dayGroups){
    $drows=@($g.Group|Sort-Object server_time);$dv=Pnls $drows;$sum=SumVals $dv;$last=$drows[-1]
    if($last.note -match 'daily_net=([-0-9\.]+)'){$reported=Num $Matches[1];if([math]::Abs($reported-$sum)-gt 0.02){$dailyMismatch++}}
  }

  # High ordinal real fills above configured maximum should never happen.
  $ordOver=0
  foreach($r in $rows | Where-Object {$_.event -eq 'REVERSAL_SIGNAL' -and $_.note -like 'TEST HIGH*'}){if((Num $r.reversal_ordinal) -gt $HighMax){$ordOver++}}

  # Actual monetary initial-risk estimate: EA validates +$1 price move = Lot/0.01 USD.
  $riskScale=$Lot/0.01
  $riskUsd=[double]$base.peak_summed_r0*$riskScale
  $riskPct=0.0;if($Deposit -gt 0){$riskPct=100.0*$riskUsd/$Deposit}

  $status='PASS'
  $hardIssues=$dupB31+$orphanParent+$unknownParent+$unclosed+$slLoosen+$postStop+$dailyMismatch+$ordOver+$dupBo
  if($hardIssues -gt 0){$status='FAIL'}elseif($missingDates.Count -gt 0 -or [int]$base.margin_blocked -gt 0){$status='WARN'}

  $summary=[pscustomobject]@{
    run_id=$RunId;phase=$PhaseName;from_date=$RunFrom;to_date=$RunTo;deposit=$Deposit;lot=$Lot;high_max=$HighMax;high_sl=$HighSL;
    net_pnl=$base.net_pnl;return_pct=$base.return_pct;trades=$base.trades;wins=$base.wins;losses=$base.losses;be=$base.be;
    gross_profit=[math]::Round($grossProfit,2);gross_loss=[math]::Round($grossLoss,2);profit_factor=[math]::Round((PF $closed),3);expectancy=[math]::Round(($base.net_pnl/[math]::Max(1,$base.trades)),3);avg_win=[math]::Round((AvgArr $pos),3);avg_loss=[math]::Round((AvgArr $neg),3);max_losing_streak=(MaxLossStreak $closed);max_realized_drawdown=[math]::Round((RealizedDD $closed),2);
    positive_days=$posDays.Count;negative_days=$negDays.Count;flat_days=$flatDays.Count;best_day_pnl=[math]::Round($bestDay,2);worst_day_pnl=[math]::Round($worstDay,2);max_daily_realized_giveback=[math]::Round($maxGiveback,2);
    reversal_trades=$base.reversal_trades;reversal_win_rate=$base.reversal_win_rate;reversal_pnl=$base.reversal_pnl;reversal_profit_factor=[math]::Round((PF $revClosed),3);
    pullback_trades=$base.pullback_trades;pullback_win_rate=$base.pullback_win_rate;pullback_pnl=$base.pullback_pnl;pullback_profit_factor=[math]::Round((PF $pbClosed),3);
    high_r1_n=$base.high_r1_n;high_r1_pnl=$base.high_r1_pnl;high_r2_n=$base.high_r2_n;high_r2_pnl=$base.high_r2_pnl;high_r3_n=$base.high_r3_n;high_r3_pnl=$base.high_r3_pnl;high_r4_n=$base.high_r4_n;high_r4_pnl=$base.high_r4_pnl;
    stacked_trades=$base.stacked_trades;stacked_pnl=$base.stacked_pnl;max_concurrent_positions=$base.max_concurrent_positions;peak_summed_r0_price=$base.peak_summed_r0;peak_initial_risk_usd=[math]::Round($riskUsd,2);peak_initial_risk_pct=[math]::Round($riskPct,2);
    max_required_new_margin=$base.max_required_new_margin;max_account_margin=$base.max_account_margin;min_free_margin=$base.min_free_margin;min_margin_level=$base.min_margin_level;margin_blocked=$base.margin_blocked;daily_loss_stop=$base.daily_loss_stop;daily_loss_would_trigger=$base.daily_loss_would_trigger;
    expected_zone_days=$ExpectedDates.Count;loaded_zone_days=$loadedDates.Count;missing_zone_days=$missingDates.Count;missing_zone_dates=($missingDates -join ';');regression_status=$status
  }
  $checks=[pscustomobject]@{run_id=$RunId;phase=$PhaseName;b31_duplicate_evaluations=$dupB31;duplicate_breakout_ids=$dupBo;pullback_parent_missing=$orphanParent;pullback_parent_unknown=$unknownParent;unclosed_positions=$unclosed;sl_loosen_violations=$slLoosen;post_daily_stop_new_entries=$postStop;daily_net_mismatches=$dailyMismatch;high_ordinal_over_limit=$ordOver;missing_zone_days=$missingDates.Count;status=$status}
  return [pscustomobject]@{Summary=$summary;Daily=@($daily);Checks=$checks}
}

Ensure-Path $TerminalExe "terminal64.exe"
Ensure-Path $MetaEditorExe "metaeditor64.exe"
Ensure-Path $DataDir "MetaTrader data directory"
Ensure-Path (Join-Path $Root "ea\$EAFileName") "Harness EA source"
Ensure-Path (Join-Path $Root "data\$RangesFileName") "ranges.csv"
$rangesPath = Join-Path $Root "data\$RangesFileName"
$allRangeDates = @(Get-EnabledRangeDates $rangesPath)
if($allRangeDates.Count -eq 0){ Fail "No enabled dates found in ranges.csv" }
Write-Host ("Range coverage available: {0} zone days, {1} .. {2}" -f $allRangeDates.Count,$allRangeDates[0].ToString("yyyy.MM.dd"),$allRangeDates[-1].ToString("yyyy.MM.dd")) -ForegroundColor DarkCyan

# To prevent /config from attaching to an already-running terminal instance, require terminal closed for Lite v1.
$running = Get-Process terminal64 -ErrorAction SilentlyContinue
if($running){ Fail "Close all terminal64.exe instances before running Harness Lite v1." }

$CommonFilesDir = Join-Path (Split-Path $DataDir -Parent) "Common\Files"
$expertDir = Join-Path $DataDir "MQL5\Experts\$ExpertFolder"
$testerProfiles = Join-Path $DataDir "MQL5\Profiles\Tester"
$filesDir = Join-Path $DataDir "MQL5\Files"
New-Item -ItemType Directory -Force -Path $expertDir,$testerProfiles,$filesDir,$CommonFilesDir,(Join-Path $Root "generated"),(Join-Path $Root "results") | Out-Null

$sourceLocal = Join-Path $Root "ea\$EAFileName"
$sourceTarget = Join-Path $expertDir $EAFileName
Copy-Item $sourceLocal $sourceTarget -Force
Copy-Item (Join-Path $Root "data\$RangesFileName") (Join-Path $filesDir $RangesFileName) -Force
Copy-Item (Join-Path $Root "data\$RangesFileName") (Join-Path $CommonFilesDir $RangesFileName) -Force

Write-Host "Compiling $sourceTarget ..." -ForegroundColor Cyan
$compileLog = [IO.Path]::ChangeExtension($sourceTarget,".log")
Remove-Item $compileLog -Force -ErrorAction SilentlyContinue
$p = Start-Process -FilePath $MetaEditorExe -ArgumentList @("/compile:`"$sourceTarget`"","/log") -Wait -PassThru
if(-not (Test-Path $compileLog)){ Fail "MetaEditor compile log was not created: $compileLog" }
$compileText = Get-Content $compileLog -Raw
if($compileText -notmatch '(?im)\b0 errors?,\s*0 warnings?\b') {
  Write-Host $compileText
  Fail "Compile Gate failed. Expected 0 errors, 0 warnings."
}
Write-Host "Compile Gate PASS: 0 errors, 0 warnings" -ForegroundColor Green

$matrix = Import-Csv (Join-Path $Root "test_matrix.csv") | Where-Object { $_.enabled -eq "1" }
if($Phase -ne "ALL") { $matrix = @($matrix | Where-Object { $_.phase -eq $Phase }) }
if($matrix.Count -eq 0){ Fail "No enabled runs for phase $Phase" }

$allResults = @()
$allDaily = @()
$allChecks = @()
foreach($row in $matrix){
  $highMax = if($row.high_max -eq "USE_CANDIDATE"){$CandidateHighMax}else{[int]$row.high_max}
  $highSL  = if($row.high_sl -eq "USE_CANDIDATE"){$CandidateHighSL}else{Num $row.high_sl}
  $runId = $row.run_id
  $runDir = Join-Path $Root "results\$runId"
  New-Item -ItemType Directory -Force -Path $runDir | Out-Null
  $setName = "$runId.set"
  $setPathGenerated = Join-Path $Root "generated\$setName"
  $setMeta = Write-SetFile $row $setPathGenerated $highMax $highSL
  Copy-Item $setPathGenerated (Join-Path $testerProfiles $setName) -Force
  $iniPath = Join-Path $Root "generated\$runId.ini"
  $dr = Resolve-DateRange $row $allRangeDates
  $expectedDates = @(Expected-Dates-InRange $allRangeDates $dr.From $dr.To)
  Write-IniFile $row $setName $iniPath $dr.From $dr.To

  # v1.3 RESUME: reuse only locally archived evidence whose INI and SET exactly match
  # the current generated scenario. This avoids rerunning completed long tests while
  # preventing stale evidence from a different configuration being accepted.
  $resumeSummary = Join-Path $runDir $setMeta.Summary
  $resumeJournal = Join-Path $runDir $setMeta.Journal
  $resumeSet = Join-Path $runDir $setName
  $resumeIni = Join-Path $runDir "$runId.ini"
  $canResume = $false
  if($Resume -and (Test-Path $resumeSummary) -and (Test-Path $resumeJournal) -and (Test-Path $resumeSet) -and (Test-Path $resumeIni)) {
    $setSame = ((Get-FileHash $resumeSet -Algorithm SHA256).Hash -eq (Get-FileHash $setPathGenerated -Algorithm SHA256).Hash)
    $iniSame = ((Get-FileHash $resumeIni -Algorithm SHA256).Hash -eq (Get-FileHash $iniPath -Algorithm SHA256).Hash)
    if($setSame -and $iniSame) { $canResume = $true }
  }
  if($canResume) {
    Write-Host "[$($row.phase)] $runId : RESUME verified cached evidence" -ForegroundColor Cyan
    $base = Analyze-Summary $runId $row.phase (Num $row.deposit) $resumeSummary
    $analysis = Analyze-Extended $base $runId $row.phase (Num $row.deposit) (Num $row.lot) $highMax $highSL $dr.From $dr.To $resumeSummary $resumeJournal $expectedDates
    $res = $analysis.Summary
    $allResults += $res
    $allDaily += @($analysis.Daily)
    $allChecks += $analysis.Checks
    Write-Host "  -> cached PnL=$($res.net_pnl) Trades=$($res.trades) PF=$($res.profit_factor) QA=$($res.regression_status)" -ForegroundColor Green
    continue
  }

  # Remove stale shared outputs before the run; EA also deletes them on OnInit.
  Remove-Item (Join-Path $CommonFilesDir $setMeta.Summary) -Force -ErrorAction SilentlyContinue
  Remove-Item (Join-Path $CommonFilesDir $setMeta.Journal) -Force -ErrorAction SilentlyContinue
  Write-Host "[$($row.phase)] $runId : Deposit=$($row.deposit) GROSS15 Cap=$($row.max_live_positions) Restart=$($row.restart_time) Dates=$($dr.From)..$($dr.To)" -ForegroundColor Yellow
  $started = Get-Date
  Start-Process -FilePath $TerminalExe -ArgumentList "/config:`"$iniPath`"" -Wait | Out-Null

  $sumFile = Find-NewestOutput $setMeta.Summary $started
  $jourFile = Find-NewestOutput $setMeta.Journal $started
  if((-not $sumFile) -or (-not $jourFile)){
    Save-Diagnostics $runDir $started
    if($jourFile){ Copy-Item $jourFile.FullName (Join-Path $runDir $setMeta.Journal) -Force }
    $missing = @()
    if(-not $sumFile){ $missing += $setMeta.Summary }
    if(-not $jourFile){ $missing += $setMeta.Journal }
    Fail "$runId tester outputs missing from Common\Files: $($missing -join ', '). Diagnostics saved under results\$runId\diagnostics"
  }
  $sumDest = Join-Path $runDir $setMeta.Summary
  $jourDest = Join-Path $runDir $setMeta.Journal
  Copy-Item $sumFile.FullName $sumDest -Force
  Copy-Item $jourFile.FullName $jourDest -Force
  Copy-Item $iniPath $runDir -Force
  Copy-Item $setPathGenerated $runDir -Force
  $base = Analyze-Summary $runId $row.phase (Num $row.deposit) $sumDest
  $analysis = Analyze-Extended $base $runId $row.phase (Num $row.deposit) (Num $row.lot) $highMax $highSL $dr.From $dr.To $sumDest $jourDest $expectedDates
  $res = $analysis.Summary
  $allResults += $res
  $allDaily += @($analysis.Daily)
  $allChecks += $analysis.Checks
  Write-Host "  -> PnL=$($res.net_pnl) Trades=$($res.trades) PF=$($res.profit_factor) RevWR=$($res.reversal_win_rate)% PBWR=$($res.pullback_win_rate)% MaxPos=$($res.max_concurrent_positions) RiskUSD=$($res.peak_initial_risk_usd) Margin=$($res.max_account_margin) QA=$($res.regression_status)" -ForegroundColor Green
}

$outCsv = Join-Path $Root "results\RESULT_MATRIX_$Phase.csv"
$dailyCsv = Join-Path $Root "results\DAILY_MATRIX_$Phase.csv"
$checkCsv = Join-Path $Root "results\REGRESSION_CHECKS_$Phase.csv"
$allResults | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $outCsv
$allDaily | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $dailyCsv
$allChecks | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $checkCsv
Write-Host ""; Write-Host "DONE -> $outCsv" -ForegroundColor Cyan
Write-Host "DAILY -> $dailyCsv" -ForegroundColor Cyan
Write-Host "QA    -> $checkCsv" -ForegroundColor Cyan
Write-Host "AR-OPS-01 FAST restart-safety matrix complete. The wrapper will build equivalence/deployment/tail-risk gates and one evidence ZIP." -ForegroundColor Cyan
