"""Domain types and schemas for the vectorized XAUUSD trading strategy."""

from .schema import (
    OrderId,
    OrderInput,
    OrderManagementResult,
    PerCandleState,
    PerTickBaseState,
    PositionId,
    PositionInput,
    PositionTrackingResult,
    PullbackWindowsTuple,
    ReferenceInput,
    ReferenceResult,
    ReversalInput,
    ReversalResult,
    SignalCandidatesTuple,
    StrategyResult,
    StrategyResultWithCandles,
    TradingAction,
    VectorizedCandleInput,
    VectorizedTickInput,
    ZoneDayInput,
)

__all__ = [
    "OrderId",
    "OrderInput",
    "OrderManagementResult",
    "PerCandleState",
    "PerTickBaseState",
    "PositionId",
    "PositionInput",
    "PositionTrackingResult",
    "PullbackWindowsTuple",
    "ReferenceInput",
    "ReferenceResult",
    "ReversalInput",
    "ReversalResult",
    "SignalCandidatesTuple",
    "StrategyResult",
    "StrategyResultWithCandles",
    "TradingAction",
    "VectorizedCandleInput",
    "VectorizedTickInput",
    "ZoneDayInput",
]
