"""Domain types and schemas for the vectorized XAUUSD trading strategy."""

from .schema import (
    OrderId,
    OrderInput,
    OrderManagementResult,
    PerCandleState,
    PerTickState,
    PositionId,
    PositionInput,
    PositionTrackingResult,
    PullbackWindowsTuple,
    ReferenceTrendInfo,
    ReversalInput,
    ReversalResult,
    SignalCandidatesTuple,
    StrategyResult,
    StrategyResultWithCandles,
    TradingAction,
    TrendInfo,
    VectorbtBacktestInput,
    VectorizedTick,
    ZoneDayInput,
)

__all__ = [
    "OrderId",
    "OrderInput",
    "OrderManagementResult",
    "PerCandleState",
    "PerTickState",
    "PositionId",
    "PositionInput",
    "PositionTrackingResult",
    "PullbackWindowsTuple",
    "TrendInfo",
    "ReferenceTrendInfo",
    "ReversalInput",
    "ReversalResult",
    "SignalCandidatesTuple",
    "StrategyResult",
    "StrategyResultWithCandles",
    "TradingAction",
    "VectorbtBacktestInput",
    "VectorizedTick",
    "ZoneDayInput",
]
