from __future__ import annotations

BASE_R_USD = 6.0
BREAKOUT_BUFFER_USD = 1.0
GROSS_DAILY_RISK_FRACTION = 0.15
PULLBACK_PENETRATION_USD = 0.20
PRE_ZONE_TRIGGER_DISTANCE_USD = 1.0
DAILY_REALIZED_LOSS_FRACTION = 0.20
PARITY_PRICE_TOLERANCE = 1e-9
MINIMUM_FREE_SPACE_USD = 3.0
